#!/bin/bash

function new () {
  cd /var/www;
  cd ~/Copy/Sites;
  DISPLAY=:0 notify-send -i ~/.fsp_laravel/console.png "Clonando...";
  git clone https://github.com/laravel/laravel.git;
  mv laravel $1;
  cd $1;
  chmod -R 777 storage; 
  cd application/tasks;
  wget https://raw.github.com/JeffreyWay/Laravel-Generator/master/generate.php;
  ln -s ~/Copy/Sites/$1 /var/www/$1;

  DISPLAY=:0 notify-send -i ~/.fsp_laravel/console.png "Se ha creado un nuevo projecto en /var/www/"$1 ;
}

function use() {
  USANDO="/var/www/"$1;
  DISPLAY=:0 notify-send -i ~/.fsp_laravel/console.png "Usando " $USANDO ;
}

#Create a resource syntax: laravel r [project name] [resource name] [actions]
function r() {
  cd /var/www/$1;
  php artisan generate:resource $2
  DISPLAY=:0 notify-send -i ~/.fsp_laravel/console.png "Resource " $2 "created";
}


$1 $2 $3 $4
