#!/bin/bash

source ~/.fsp_laravel/settings

# Function to create a new project. Syntax: laravel new [project name]
function new () {
  cd $LOCATION;
  DISPLAY=:0 notify-send -i ~/.fsp_laravel/console.png "Cloning into $LOCATION ... please wait.";
  git clone https://github.com/laravel/laravel.git;
  mv laravel $1;
  cd $1;
  chmod -R 777 storage; 
  cd application/tasks;
  wget https://raw.github.com/JeffreyWay/Laravel-Generator/master/generate.php;
  ln -s $LOCATION/$1 $DESTINATION/$1;

  DISPLAY=:0 notify-send -i ~/.fsp_laravel/console.png "New project created in $DESTINATION/"$1 ;
}

#Create a resource syntax: laravel r [project name] [resource name] [actions]
function r() {
  cd $DESTINATION/$1;
  php artisan generate:resource $2
  DISPLAY=:0 notify-send -i ~/.fsp_laravel/console.png "Resource " $2 "created";
}

function assets() {
  cd $LOCATION/$1;
  php artisan generate:assets $2 $3 $4 $5
  DISPLAY=:0 notify-send -i ~/.fsp_laravel/console.png "Created assets";
}

$1 $2 $3 $4 $5
